### ISSUE TITLE
Button text isn't readable in dark mode

### ISSUE THREAD

**Issue by RebeccaStevens** [5axes/TabPlus#4]
I'm not sure if this is a problem with cura itself or not but this is what it looks like:

![image](https://user-images.githubusercontent.com/7224206/178147503-835c2b5f-7fd9-4b2b-a198-a220d2421cd7.png)

**Comment by 5axes** [comment]
Not really a bug , but must be solved in a futur release

**Comment by 5axes** [comment]
Same in 4.13 it's Ok 
![image](https://user-images.githubusercontent.com/11015345/178241530-0308b192-5973-4618-b576-4ee15ff1f5f5.png)

**Comment by RebeccaStevens** [comment]
Hmm, that's weird. I guess it's an issue with cura itself. I'm using version 5.1.0-beta+304

Feel free to close this.

**Comment by 5axes** [comment]
Yes Strange , 5.1 Beta it's also ok for me 
![image](https://user-images.githubusercontent.com/11015345/178248377-d8f953be-923d-4d39-a8fc-aaacd478838b.png)
In your screenshot the background looks like transparent ?? Could be the origine of your issue but I cannot reproduce. Something regarding your graphic card ? 
As I'm not using some special settings this issue should be in that case also present ont the other toolbar function or is it just an issue regarding my plugins ?

**Comment by 5axes** [comment]
The "Per Model Settings" dialog windows , also have a button . But as they use a different style it's perhap's different.
![image](https://user-images.githubusercontent.com/11015345/178250809-b158de7f-a7e8-4765-b6b1-cc1568be2bd6.png)

**Comment by RebeccaStevens** [comment]
Yeah, that button looks fine. Though I did just notice another button from another plugin has the same issue.

**Comment by RebeccaStevens** [comment]
I just switched to light mode and the buttons have the same issue...
Idk what's causing it.

**Comment by 5axes** [comment]
Ok "fixed" by using the same button style . But not solved the issue of the dialog transparency 
![image](https://user-images.githubusercontent.com/11015345/178264422-027156d3-478d-460c-87d1-ca902b8c6b04.png)

**Comment by shimoni-shaked** [comment]
I also have the same issue. Cura 5.0.0, installed your latest version from the marketplace.

**Comment by 5axes** [comment]
button or transparency ?

**Comment by shimoni-shaked** [comment]
transparency 
![image](https://user-images.githubusercontent.com/51531847/188273798-162aa955-c38b-4cca-b79e-074e88de0fd5.png)

**Comment by 5axes** [comment]
Sorry but it's working fine for me.  Check if your release is the 1.0.4 this issue has been solved with this release.
![image](https://user-images.githubusercontent.com/11015345/188334140-7a345380-7f76-458e-862e-dfe0ecb83ebc.png)

**Comment by shimoni-shaked** [comment]
The release is 1.0.4, the latest version on the marketplace. How can I update it?

**Comment by 5axes** [comment]
Yes it's currently still the 1.0.4  , Ultimaker have to validate the plugin before to release it on the marketplace , can take between 10 days and 1 month.

**Comment by 5axes** [comment]
This times it was much more faster . V1.0.5 is on line
